# !!! exampleSite only, set this to your own site URL
baseURL= "https://arts-link.github.io/ryder/"
languageCode= "en-us"
title= "Ryder hugo theme example site"
theme= ["ryder"]
summaryLength = 15
enableRobotsTXT = true
# paginate = 4

# !!! exampleSite only, you may need to delete the line: `themesDir: ../../` 
themesDir= "../../"
[params]
  # dark mode switch defaults to hidden, remove this line or set to false to hide
  # alternatively, and probably more useful, use system dark mode by removing darkMode: 'class', from tailwind.config.js
  showDarkToggle = true 
  headerGradientClasses = "bg-gradient-to-r from-rose-500 to-rose-800" 
  # defaults to false if not set.
  # enableDebugPanel = true 
[[params.alphaAlert]]
  weight = 11
  alertType = "danger"
  alertTitle = "Global Banners"
  alertMessage = "This theme is a work in progress! <a href='/posts/alerts' class='underline'>learn more about them!</a>"
  alertIconClass = "fa-solid fa-camera-retro"
[[params.alphaAlert]]
  weight = 1
  alertType = "info"
  alertTitle = "2 Global Banners are possible"
  alertMessage = "Just add them to [params.alphaAlert] in hugo.toml. <a href='/posts/alerts' class='underline'>learn more about them!</a>"
  alertIconClass = "fa-solid fa-camera-retro"
[[params.social]]
  faClasses = "fa-solid fa-envelope"
  title = "Email me"
  url   = "mailto:hello@arts-link.com?subject=web"
  target= "_blank"
  weight = 30 
[[params.social]]
  faClasses = "fa-brands fa-github"
  title = "GitHub"
  url   = "https://www.github.com/arts-link"
  target= "_blank"
  weight = 20
