baseURL= "https://arts-link.github.io/"
languageCode= "en-us"
title= "Ryder example site"
theme= "ryder"
summaryLength = 15

# !!! exampleSite only, you may need to delete the line: `themesDir: ../../` 
themesDir= "../../"
[params]
  description = "Lightning Fast Portfolios for Artists"
  isAlpha = true
[[params.alphaAlert]]
  alertType = "danger"
  alertTitle = "Special Banner add-on"
  alertMessage = "This theme is a work in progress!"
  alertIconClass = "fa-solid fa-camera-retro"
[[params.social]]
  faClasses = "fa-solid fa-envelope"
  title = "Email me"
  url   = "mailto:hello@arts-link.com?subject=web"
  target= "_blank"
  weight = 30 
[[params.social]]
  faClasses = "fa-brands fa-github"
  title = "GitHub"
  url   = "https://www.github.com/arts-link"
  target= "_blank"
  weight = 20