baseURL= "https://arts-link.github.io/ryder/"
languageCode= "en-us"
title= "Ryder example site"
theme= "ryder"

# !!! exampleSite only, you may need to delete the line: `themesDir: ../../` 
themesDir= "../../"

